Updates on KWS, MSnoise, Signalmixer Data Loaders & Evaluation Notebook, New Scripts for Mixed Signals
analogdevicesinc/ai8x-training pull request #299
Opened 2024-03-13 11:15 UTC by EyubogluMerve

## Updates 

- Updates on ***kws20.py***:
    - Dataset functions for signalmixer are added to the KWS data loader.
    - White Noise application is updated using SNR levels (generated between [-5, 20] dB).
- Updates on ***msnoise.py***:
    - Unnecessary reading operations are removed (**filter_classes** & **filter_dtype**)
    - A probability array is added as a parameter to MSnoise class. (Holds the noise type probabilities)
    - Naming differences in the raw Train/Test data are handled during download operation.
- Updates on ***signalmixer.py***:
    - Several parameters are implemented:
        ***apply_prob***: noise application probability (0.8, default)
        ***snr_range***: SNR range to be applied to the dataset ([-5 ,10] dB SNR, default)
        ***noise_type***: array that contains the noise type names (All Noise Types, default)

- Evaluation Notebook for KWS is updated.
- Scripts for KWS NAS & v3 models are added for mixing with MSnoise applications.

2024-03-13 14:34 UTC, rotx-maxim requested changes
This is missing the changes from #266, #269, and possibly #280.

2024-03-20 14:52 UTC, alicangok requested changes
Could you also have a look at `scripts/evaluate_kws20_v3_SNR10dB.sh`, and check that the `MixedKWS20_10dB` dataset still works, with all the changes we made to the kws20 and msnoise datasets?

Even better, I think it would be best if we move the `MixedKWS20_10dB` dataset into `signalmixer.py` for backward compatibility purposes, then delete the unmaintained `mixedkws.py`. Having two files for the same purpose can be confusing.

2024-03-20 14:52 UTC, alicangok commented on datasets/msnoise.py
> +            inp = inp / 256
Please convert this to the original version.

2024-03-20 14:52 UTC, alicangok commented on datasets/msnoise.py
> +                print('Sum of the probabilities is not 1!')
Also print a helpful note to the user, such as "Carrying out the proper normalization"

2024-03-20 14:52 UTC, alicangok commented on datasets/signalmixer.py
> +    def single_snr_mixer(self, signal):
Consider renaming this function to simply "snr_mixer"

2024-03-20 14:52 UTC, alicangok commented on datasets/signalmixer.py
> +        cleanfactor = 10**(snr_val/20)
For better readability, consider keeping the `self.snr_range` variable (don't assign it to `snr`), and replacing `snr_val` with `snr`.

2024-03-20 23:36 UTC, EyubogluMerve commented
> Could you also have a look at `scripts/evaluate_kws20_v3_SNR10dB.sh`, and check that the `MixedKWS20_10dB` dataset still works, with all the changes we made to the kws20 and msnoise datasets?
> 
> Even better, I think it would be best if we integrate `MixedKWS20_10dB` dataset into `signalmixer.py` for backward compatibility purposes, then delete the unmaintained `mixedkws.py`. Having two files for the same purpose can be confusing.

I created the same dataset `(MixedKWS20_10dB)` using `signalmixer.py` data loader under `kws20.py` file. Also, I removed the `mixedkws.py`.  In addition, I made some fixes in `msnoise.py` & `kws20.py`. 

I checked all the evaluation and training scripts just in case. They're all working correctly.

2024-03-21 13:33 UTC, rotx-maxim requested changes
Please address https://github.com/MaximIntegratedAI/ai8x-training/pull/299#pullrequestreview-1934358167

2024-03-21 15:38 UTC, alicangok commented on notebooks/KWS_Noise_Evaluation.ipynb
I would suggest the following replacement text for introducing signalmixer:

"The signalmixer data loader has several parameters:
 
- The `apply_prob` parameter determines the percentage of the samples on which additive noise will be applied (default setting: 0.8 (%80))
- The `snr_range` parameter modifies the additive noise power, such that the resulting signal falls between the specified SNR limits (default setting: [-5, 10] dB SNR)
- The `noise_type` parameter can be used provide a list of noise types to be applied (default setting is to apply all possible noise types in the dataset).

2024-05-23 13:30 UTC, ermanok reviewed
Minor suggestions for code refactor.

2024-05-23 13:30 UTC, ermanok commented on datasets/signalmixer.py
> +        rmsclean = torch.sqrt(torch.mean(signal**2))
Please check the variable names like follows:
rmsclean -> rms_clean
scalarclean -> scalar_clean

2024-05-31 20:08 UTC, rotx-maxim requested changes

2024-05-31 20:08 UTC, rotx-maxim commented on datasets/kws20.py
> +            if len(classes) == 35:
Can we parametrize this instead of hardcoding a number of classes?

2024-05-31 20:08 UTC, rotx-maxim commented on datasets/kws20.py
> +    elif num_classes == 35:
see earlier comment

2024-06-03 21:42 UTC, ermanok requested changes
Could you please add `--print-freq 100` to the training scripts? Now, the logs are too long to go over...

2024-06-17 15:47 UTC, alicangok commented
@EyubogluMerve, could you please update your PR with the following patch I created?: [MervePR.patch](https://github.com/user-attachments/files/15873487/MervePR.patch)

List of changes:
- class names now follow the original dataset convention (e.g. `SILENCE` -> `_silence_`)
- training and validation examples for the `_silence_` class now come from all possible `_background_noise_` types, instead of exclusively using `running_tap` for validation (as we discussed in Teams)
- set `download=True` for the MSNoise dataset
- modifications and additions to comments and printed logs

---

Note: This PR contains the `train_kws12_nas_benchmark.sh` script, which requires a model checkpoint for the 12-class case which currently does not exist in the [ongoing PR to the synthesis repo](https://github.com/analogdevicesinc/ai8x-synthesis/pull/332). We will either need to remove this script from this PR, or add the trained checkpoint file to the synthesis repo. (If we decide on the latter, I will make a separate PR to the synthesis repo)

2024-06-24 18:44 UTC, alicangok commented
@EyubogluMerve, could you apply [MervePR2.patch](https://github.com/user-attachments/files/15960033/MervePR2.patch) and update the PR?

This patch introduces constants to deal with the "data_type"s and replaces the `|` with the explicit `torch.logical_or()` for better readability.

2024-06-27 20:45 UTC, rotx-maxim approved these changes

2024-06-28 16:19 UTC, merged