QRCode Detection Model
analogdevicesinc/ai8x-training pull request #312
Opened 2024-05-20 13:45 UTC by ermanok

2024-05-21 19:29 UTC, rotx-maxim requested changes

2024-05-21 19:29 UTC, rotx-maxim commented on requirements.txt
Can we fix qrcode to ==7.4.2

2024-05-21 19:29 UTC, rotx-maxim commented on utils/WBAugmenter/WBEmulator.py
We need to add the LICENSE file text to this file

2024-05-21 19:29 UTC, rotx-maxim commented on utils/WBAugmenter/imresize.py
Fix 20242024

2024-05-28 11:16 UTC, ermanok commented on requirements.txt
Sure

2024-05-28 11:16 UTC, ermanok commented on utils/WBAugmenter/imresize.py
fixed

2024-06-04 19:17 UTC, rotx-maxim approved these changes

2024-06-05 08:07 UTC, seldauyanik-maxim approved these changes

2024-06-05 19:43 UTC, merged