Face Detection Library Replacement #2
analogdevicesinc/ai8x-training pull request #320
Opened 2024-06-25 08:52 UTC by oguzhanbsolak

Due to the broken checkpoint links, the face-detection library has been replaced with the batch-face. The batch-face provides the same speed and detection performance and keeps checkpoints on GitHub.

2024-06-25 13:24 UTC, rotx-maxim requested changes

2024-06-25 13:24 UTC, rotx-maxim commented on datasets/vggface2.py
> +            detector = RetinaFace(gpu_id=-1, network="resnet50")
We need to modify this logic slightly. Currently, it's possible to specify "no GPU" even if one is available.
args.device in train.py holds the result of that logic.

2024-06-25 15:13 UTC, rotx-maxim approved these changes

2024-06-26 06:41 UTC, ermanok approved these changes
Looks good.

2024-06-26 13:31 UTC, merged