Pytorch 2 Face Detection Library Change
analogdevicesinc/ai8x-training pull request #321
Opened 2024-06-25 09:30 UTC by oguzhanbsolak

1- Similar to the  [1.8](https://github.com/analogdevicesinc/ai8x-training/pull/320) replacement, face-detection library has been changed with the batch-face.

2- Added the missing parts of relation-based knowledge distillation from 1.8.

2024-06-25 13:26 UTC, rotx-maxim requested changes

2024-06-25 13:26 UTC, rotx-maxim commented on datasets/vggface2.py
> +
Adjust logic similar to #320

2024-06-25 15:32 UTC, rotx-maxim requested changes

2024-06-25 15:32 UTC, rotx-maxim commented on requirements.txt
> +batch-face>=1.4.0
Please pin version for the pytorch-2 branch

2024-06-25 15:56 UTC, rotx-maxim approved these changes

2024-06-26 07:00 UTC, ermanok approved these changes
looks good

2024-06-26 13:32 UTC, merged